<Project Sdk="Microsoft.NET.Sdk.Web">
	<PropertyGroup Label="Globals">
		<SccProjectName>SAK</SccProjectName>
		<SccProvider>SAK</SccProvider>
		<SccAuxPath>SAK</SccAuxPath>
		<SccLocalPath>SAK</SccLocalPath>
	</PropertyGroup>
	<PropertyGroup>
		<TargetFramework>net8.0-windows7.0</TargetFramework>
		<ErrorOnDuplicatePublishOutputFiles>false</ErrorOnDuplicatePublishOutputFiles>
	</PropertyGroup>
	<PropertyGroup>
		<PublishWithAspNetCoreTargetManifest>false</PublishWithAspNetCoreTargetManifest>
	</PropertyGroup>
	<ItemGroup>

		<PackageReference Include="Swashbuckle.AspNetCore" Version="6.8.1" />
		<PackageReference Include="Swashbuckle.AspNetCore.Newtonsoft" Version="6.8.1" />
		<PackageReference Include="WebMarkupMin.AspNetCore3" Version="2.17.0" />
		<PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="8.0.10" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
		<PackageReference Include="System.Private.ServiceModel" Version="4.10.3" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\Oversite.Core\Oversite.Core.csproj" />
	</ItemGroup>
</Project>